dist: xenial

language: cpp
compiler: gcc

script:
  - sudo apt-get install libgtest-dev
  - make
  - make test
  - ./bin/testprog.exe
  - git ls-files gavnovtoroe/cs/ | xargs clang-format -i && git diff --exit-code
